config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bulletin
  #match ':controller(/:action(/:id(.:format)))', :via => :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bulletin_controller.rb
class BulletinController < ApplicationController
    def index
       @news = Board.where(:new => 1)
       @update = Board.where(:new => 0)
    end
    def new
        @boards = Board.new
    end
    def create
        @boards = Board.new(board_params)
        @boards.new = params[:new]
        @boards.save
        redirect_to bulletin_index_path
    end
    def edit
        @boards = Board.find(params[:id])
    end
    def update
        @boards = Board.find(params[:id])
        @boards.update(board_params)
        @boards.save
        redirect_to bulletin_index_path
    end
    def destroy
        @event = Board.find(params[:id])
        @event.destroy
        redirect_to bulletin_index_path
    end

    private
    def board_params
    params.require(:board).permit(:description,:year,:month,:day,:new)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulletin_helper.rb
module BulletinHelper
end

app/views/bulletin/edit.html.erb
<%= form_for @boards , :url => bulletin_path(@boards), :method => :patch do |f| %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.label :year, "year" %>
    <%= f.text_field :year %>

    <%= f.label :month, "Month" %>
    <%= f.text_field :month %>

    <%= f.label :day, "day" %>
    <%= f.text_field :day %>

    <%= f.label :new, "移到最新消息:1 移到網站改版:0" %>
    <%= f.text_field :new %>
    <%= f.submit "Create" %>
<% end %>

app/views/bulletin/index.html.erb
<ul>
<h1>最新消息<h1>
<% @news.each do |b| %>
  <li>
      <p>
 	   <%= b.description %>
       <%= b.year %>/
       <%= b.month %>/
       <%= b.day %>
       <%= link_to 'delete', bulletin_path(b) , :method => :delete %>
       <%= link_to 'edit', edit_bulletin_path(b) %>
       </p>
  </li>
<% end %>

<h1>網頁改版<h1>
<% @update.each do |b| %>
  <li>
      <p>
 	   <%= b.description %>
       <%= b.year %>/
       <%= b.month %>/
       <%= b.day %>
       <%= link_to 'delete', bulletin_path(b) , :method => :delete%>
       <%= link_to 'edit', edit_bulletin_path(b) %>
       </p>
  </li>
<% end %>

 <%= link_to '新增最新消息', new_bulletin_path(new: 1) %>
 <%= link_to '新增網頁改版', new_bulletin_path(new: 0) %>
</ul>

app/views/bulletin/new.html.erb
<%= form_for @boards, :url => bulletin_index_path do |f| %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.label :year, "year" %>
    <%= f.text_field :year %>

    <%= f.label :month, "Month" %>
    <%= f.text_field :month %>

    <%= f.label :day, "day" %>
    <%= f.text_field :day %>

    <%= f.submit "Create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>